### ISSUE TITLE
Hvert enkelt fag...

### ISSUE THREAD

**Issue by skandix** [oal/timeplan-uia#1]
er det muligt å legge til slik at det er mulig å laste ned planen for hvert enkelt fag 
(at man kan legge til ekstra argument f.eks --subject DAT234), slik at man kan lage litt mer 
"customized" timeplaner om man tar fag som ikke egentlig er i den fagplanen fra før av...?

**Comment by oal** [comment]
Jeg lagde en liten workaround for dette i fjor. Litt krunglete, men inntil jeg får laget en bedre løsning kan du prøve dette:

Gå inn på fagets side på UiA.no og trykk timeplan i menyen til høyre: F.eks. http://www.uia.no/studieplaner/topic/DAT220-G

Kjør timeplan-uia med timeplan-URLen slik (cd inn i timeplan-uia-mappa først):

```
timeplan-uia -url "http://timeplan.uia.no/swsuiah/XMLEngine/default.aspx?ModuleByWeek&p1=;DAT220-G;&p2=32;33;34;35;36;37;38;39;40;41;42;43;44;45;46;47;48;49;50;51"
```

Så får du en fil `DAT220-G - Videregående programmering.csv` som du kan importere i Google Calendar.

Si fra hvis ikke det fungerer.

**Comment by oal** [comment]
Hei igjen.

Nå kan du få timeplaner for hvert enkelt fag via denne repoen: https://github.com/oal/timeplan-uia-2

Lagde altså en ny timeplan-greie i Python. Kan også brukes fra nettleseren her: http://timeplaner.olav.it/
